@startuml
package "Aplicación Django (monorepo)" {
  [cursos] --> [estudiantes]
  [profesores] --> [cursos]
  [anuncios] --> [webpage]
  [eventos]  --> [webpage]
  [inventario] --> [laboratorios]
  [practica_profesional] --> [alumni]
  [atributos] <<library>>
}
database "PostgreSQL" as DB
[Gunicorn + Django] --> DB
@enduml