version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: crmdb
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: crmpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - crm_network

  web:
    build: .
    command: gunicorn crm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_DB_NAME: crmdb
      DJANGO_DB_USER: crmuser
      DJANGO_DB_PASSWORD: crmpassword
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
    depends_on:
      - db
    networks:
      - crm_network

networks:
  crm_network:

volumes:
  postgres_data:
